
package interfaces;

import javax.swing.JOptionPane;

public class Registro extends javax.swing.JDialog {
    
    /**
     * Creates new form Registro
     */
    public Registro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //Esta linea se pone para que la ventana salga centrada.
        
        /**
         * Asegura que todas las cajas empiecen con la visibilidad esperada
         */
        Object tipoDeUsuario;
        tipoDeUsuario = jComboBoxAdministradorCliente.getSelectedItem();
        if(tipoDeUsuario=="Empresa"){
            jLabelDNI.setVisible(false);
            jTextFieldDNI.setVisible(false);
            jLabelCIF.setVisible(true);
            jTextFieldCIF.setVisible(true);
            jLabelWeb.setVisible(true);
            jTextFieldWeb.setVisible(true);
        }
        else if(tipoDeUsuario == "Particular"){
            jLabelDNI.setVisible(true);
            jTextFieldDNI.setVisible(true);
            jLabelCIF.setVisible(false);
            jTextFieldCIF.setVisible(false);
            jLabelWeb.setVisible(false);
            jTextFieldWeb.setVisible(false);
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRegistro = new javax.swing.JLabel();
        jLabelDNI = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCorreoElectronico = new javax.swing.JLabel();
        jLabelContrasena = new javax.swing.JLabel();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldCorreoElectronico = new javax.swing.JTextField();
        jTextFieldContrasena = new javax.swing.JTextField();
        jTextFieldDireccion = new javax.swing.JTextField();
        jToggleButtonSiguiente = new javax.swing.JToggleButton();
        jLabelTieneCuentaPregunta = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxAdministradorCliente = new javax.swing.JComboBox<>();
        jLabelTipoDeCuenta = new javax.swing.JLabel();
        jLabelWeb = new javax.swing.JLabel();
        jTextFieldWeb = new javax.swing.JTextField();
        jLabelCIF = new javax.swing.JLabel();
        jTextFieldCIF = new javax.swing.JTextField();
        jFormattedTextFieldTelefono = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelRegistro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelRegistro.setForeground(new java.awt.Color(51, 153, 255));
        jLabelRegistro.setText("REGISTRO");

        jLabelDNI.setText("DNI:");

        jLabelNombre.setText("Nombre:");

        jLabelCorreoElectronico.setText("Correo electrónico:");

        jLabelContrasena.setText("Contraseña");

        jLabelDireccion.setText("Dirección");

        jLabelTelefono.setText("Teléfono:");

        jTextFieldDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDNIActionPerformed(evt);
            }
        });

        jTextFieldCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoElectronicoActionPerformed(evt);
            }
        });

        jToggleButtonSiguiente.setText("SIGUIENTE");
        jToggleButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonSiguienteActionPerformed(evt);
            }
        });

        jLabelTieneCuentaPregunta.setForeground(new java.awt.Color(50, 150, 180));
        jLabelTieneCuentaPregunta.setText("¿Ya tiene una cuenta?");

        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxAdministradorCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empresa", "Particular" }));
        jComboBoxAdministradorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdministradorClienteActionPerformed(evt);
            }
        });

        jLabelTipoDeCuenta.setText("Tipo de cuenta");

        jLabelWeb.setText("Web:");

        jLabelCIF.setText("CIF:");

        jTextFieldCIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCIFActionPerformed(evt);
            }
        });

        jFormattedTextFieldTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelDNI)
                            .addComponent(jLabelCorreoElectronico)
                            .addComponent(jLabelContrasena)
                            .addComponent(jLabelDireccion)
                            .addComponent(jLabelTelefono)
                            .addComponent(jLabelTipoDeCuenta)
                            .addComponent(jLabelWeb)
                            .addComponent(jLabelCIF))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDNI)
                            .addComponent(jTextFieldNombre)
                            .addComponent(jTextFieldCorreoElectronico)
                            .addComponent(jTextFieldContrasena)
                            .addComponent(jTextFieldDireccion)
                            .addComponent(jComboBoxAdministradorCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldWeb, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(jTextFieldCIF)
                            .addComponent(jFormattedTextFieldTelefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelTieneCuentaPregunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabelRegistro))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jToggleButtonSiguiente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipoDeCuenta)
                    .addComponent(jComboBoxAdministradorCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCIF)
                    .addComponent(jTextFieldCIF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDNI)
                    .addComponent(jTextFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCorreoElectronico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContrasena))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDireccion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefono)
                    .addComponent(jFormattedTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelWeb))
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonSiguiente)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabelTieneCuentaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonSiguienteActionPerformed
        // TODO add your handling code here:
        /**
         * 
         * Se comprueba que el numero de telefono sean numeros
         */
        boolean numInvalido = false;
        try{
            for (int i = 0; i < jFormattedTextFieldTelefono.getText().length(); i++) {
                int telefonoInt = Integer.parseInt(jFormattedTextFieldTelefono.getText());
        }
        } catch(NumberFormatException e){
            numInvalido = true;
        }
        Object tipoDeUsuario;
        tipoDeUsuario = jComboBoxAdministradorCliente.getSelectedItem();
        /**
         * Se comprueba que todos los datos se introduzcan y sean validos
         */
        if( 
                
                (tipoDeUsuario=="Empresa" && (jTextFieldCIF.getText().isBlank()||jTextFieldWeb.getText().isBlank()))  
                || (tipoDeUsuario=="Particular" && (jTextFieldDNI.getText().isBlank()))){
            JOptionPane.showMessageDialog(this, "Rellena todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(    
                 jTextFieldNombre.getText().isBlank()||
                 jTextFieldCorreoElectronico.getText().isBlank() ||
                 jTextFieldContrasena.getText().isBlank()|| 
                 jTextFieldDireccion.getText().isBlank()||
                 jFormattedTextFieldTelefono.getText().isBlank())
                 
         { 
              JOptionPane.showMessageDialog(this, "Rellena todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(tipoDeUsuario=="Particular" && jTextFieldDNI.getText().contains(" ")){  //Luego se comprueba que el dni sea correcto
                JOptionPane.showMessageDialog(this, "El DNI no puede tener espacios", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(tipoDeUsuario=="Empresa" &&jTextFieldCIF.getText().contains(" ")){  //Luego se comprueba que el correo sea correcto
                JOptionPane.showMessageDialog(this, "El CIF no puede tener espacios", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(tipoDeUsuario=="Empresa" &&jTextFieldWeb.getText().contains(" ")){  //Luego se comprueba que el correo sea correcto
                JOptionPane.showMessageDialog(this, "La web no puede tener espacios", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(jTextFieldCorreoElectronico.getText().contains(" ")){  //Luego se comprueba que el correo sea correcto
                JOptionPane.showMessageDialog(this, "El correo no puede tener espacios", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(jTextFieldContrasena.getText().contains(" ")){  //Luego se comprueba que el correo sea correcto
                JOptionPane.showMessageDialog(this, "La contraseña no puede tener espacios", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(jTextFieldDireccion.getText().contains(" ")){  //Luego se comprueba que el correo sea correcto
                JOptionPane.showMessageDialog(this, "La dirección no puede tener espacios", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(jFormattedTextFieldTelefono.getText().contains(" ")){  //Luego se comprueba que el correo sea correcto
                JOptionPane.showMessageDialog(this, "El teléfono no puede tener espacios", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else
        if(numInvalido || jFormattedTextFieldTelefono.getText().length()!=9){
            JOptionPane.showMessageDialog(this, "El teléfono debe ser valido. Nueve numeros enteros seguidos", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jToggleButtonSiguienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDNIActionPerformed

    private void jComboBoxAdministradorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdministradorClienteActionPerformed
        // TODO add your handling code here:
        /**
         * Asegura que dependiendo del tipo se activen las debidas cajas.
         */
        Object tipoDeUsuario;
        tipoDeUsuario = jComboBoxAdministradorCliente.getSelectedItem();
        if(tipoDeUsuario=="Empresa"){
            jLabelDNI.setVisible(false);
            jTextFieldDNI.setVisible(false);
            jLabelCIF.setVisible(true);
            jTextFieldCIF.setVisible(true);
            jLabelWeb.setVisible(true);
            jTextFieldWeb.setVisible(true);
        }
        else if(tipoDeUsuario == "Particular"){
            jLabelDNI.setVisible(true);
            jTextFieldDNI.setVisible(true);
            jLabelCIF.setVisible(false);
            jTextFieldCIF.setVisible(false);
            jLabelWeb.setVisible(false);
            jTextFieldWeb.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxAdministradorClienteActionPerformed

    private void jTextFieldCIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCIFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCIFActionPerformed

    private void jTextFieldCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoElectronicoActionPerformed

    private void jFormattedTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registro dialog = new Registro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxAdministradorCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefono;
    private javax.swing.JLabel jLabelCIF;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelCorreoElectronico;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTieneCuentaPregunta;
    private javax.swing.JLabel jLabelTipoDeCuenta;
    private javax.swing.JLabel jLabelWeb;
    private javax.swing.JTextField jTextFieldCIF;
    private javax.swing.JTextField jTextFieldContrasena;
    private javax.swing.JTextField jTextFieldCorreoElectronico;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldWeb;
    private javax.swing.JToggleButton jToggleButtonSiguiente;
    // End of variables declaration//GEN-END:variables
}
