/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaces;

/**
 *
 * @author nicol
 */
public class Tarjeta extends javax.swing.JDialog {

    /**
     * Creates new form Tarjeta
     */
    public Tarjeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1DatosBancarios = new javax.swing.JLabel();
        jLabel2TitularDeLaCuenta = new javax.swing.JLabel();
        jLabel3NumeroTarjetaDeCrédito = new javax.swing.JLabel();
        jLabel4FechaDeCaducidad = new javax.swing.JLabel();
        jTextField1TitularDeLaCuenta = new javax.swing.JTextField();
        jFormattedTextField1NumeroTarjetaDeCrédito = new javax.swing.JFormattedTextField();
        jFormattedTextField2FechaDeCaducidad = new javax.swing.JFormattedTextField();
        jButton1Validar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1DatosBancarios.setFont(new java.awt.Font("Microsoft YaHei", 1, 24)); // NOI18N
        jLabel1DatosBancarios.setForeground(new java.awt.Color(44, 160, 201));
        jLabel1DatosBancarios.setText("DATOS BANCARIOS");

        jLabel2TitularDeLaCuenta.setText("Titular de la cuenta:");

        jLabel3NumeroTarjetaDeCrédito.setText("Numero tarjeta de crédito:");

        jLabel4FechaDeCaducidad.setText("Fecha de caducidad:");

        jTextField1TitularDeLaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1TitularDeLaCuentaActionPerformed(evt);
            }
        });

        jFormattedTextField1NumeroTarjetaDeCrédito.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jFormattedTextField2FechaDeCaducidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("################"))));

        jButton1Validar.setText("VALIDAR");
        jButton1Validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextField2FechaDeCaducidad, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jTextField1TitularDeLaCuenta)
                                    .addComponent(jFormattedTextField1NumeroTarjetaDeCrédito)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel1DatosBancarios))
                                    .addComponent(jLabel4FechaDeCaducidad))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2TitularDeLaCuenta)
                                        .addComponent(jLabel3NumeroTarjetaDeCrédito))
                                    .addGap(168, 168, 168)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jButton1Validar)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1DatosBancarios)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2TitularDeLaCuenta)
                    .addComponent(jTextField1TitularDeLaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3NumeroTarjetaDeCrédito)
                    .addComponent(jFormattedTextField2FechaDeCaducidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4FechaDeCaducidad)
                    .addComponent(jFormattedTextField1NumeroTarjetaDeCrédito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jButton1Validar)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1TitularDeLaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1TitularDeLaCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1TitularDeLaCuentaActionPerformed

    private void jButton1ValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ValidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ValidarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tarjeta dialog = new Tarjeta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Validar;
    private javax.swing.JFormattedTextField jFormattedTextField1NumeroTarjetaDeCrédito;
    private javax.swing.JFormattedTextField jFormattedTextField2FechaDeCaducidad;
    private javax.swing.JLabel jLabel1DatosBancarios;
    private javax.swing.JLabel jLabel2TitularDeLaCuenta;
    private javax.swing.JLabel jLabel3NumeroTarjetaDeCrédito;
    private javax.swing.JLabel jLabel4FechaDeCaducidad;
    private javax.swing.JTextField jTextField1TitularDeLaCuenta;
    // End of variables declaration//GEN-END:variables
}
